name: SpawnPlugin
version: ${project.version}
main: de.tdrstudios.tdrminecrft.ca.spawn.SpawnPlugin
api-version: 1.15
authors: [TDRStudios]
website: https://tdrstudios.de
default-permission: op
commands:
  spawn:
    description: Teleport to the spawn!
    usage: /spawn <Player>
  setspawn:
    description: soon
    usage: /setspawn